### ISSUE TITLE
config-lite load `development` failed

### ISSUE THREAD

**Issue by mmming0821** [nswbmw/config-lite#5]
Error: Cannot find module 'development' from '/Users/ming/Documents/test/app-vue'
    at Function.module.exports [as sync] (/Users/ming/Documents/test/app-vue/node_modules/config-lite/node_modules/resolve/lib/sync.js:33:11)
    at loadConfig (/Users/ming/Documents/test/app-vue/node_modules/config-lite/index.js:32:26)
    at Object.<anonymous> (/Users/ming/Documents/test/app-vue/node_modules/config-lite/index.js:18:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ming/Documents/test/app-vue/server.js:6:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
安装后建了：
config/default.js
  module.exports = {
   port: 3000
 }
server.js
 const config = require('config-lite')

**Comment by nswbmw** [comment]
更新 config-lite@1.6.0 试试
